version: "3.9"
services:
  scenetext_service:
    build: .
    volumes:
      - /app/weights
      - ./app:/app
    ports:
      - "8082:80"
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]