DEEPTEXT:
  Transformation: TPS # TPS | None
  FeatureExtraction: ResNet # ResNet| VGG | RCNN
  SequenceModeling: BiLSTM # BiLSTM | None
  Prediction: CTC # CTC | Attn
  rgb: false
  # character: "aAàÀảẢãÃáÁạẠăĂằẰẳẲẵẴắẮặẶâÂầẦẩẨẫẪấẤậẬbBcCdDđĐeEèÈẻẺẽẼéÉẹẸêÊềỀểỂễỄếẾệỆfFgGhHiIìÌỉỈĩĨíÍịỊjJkKlLmMnNoOòÒỏỎõÕóÓọỌôÔồỒổỔỗỖốỐộỘơƠờỜởỞỡỠớỚợỢpPqQrRsStTuUùÙủỦũŨúÚụỤưƯừỪửỬữỮứỨựỰvVwWxXyYỳỲỷỶỹỸýÝỵỴzZ0123456789!\"#$%&''()*+,-./:;<=>?@[\]^_`{|}~ "
  workers: 4
  batch_size: 192
  batch_max_length: 25
  imgH: 32
  imgW: 100
  sensitive: true
  PAD: true
  num_fiducial: 20
  input_channel: 1
  output_channel: 512
  hidden_size: 256
  saved_model: ./models/deeptext_TPS-ResNet-BiLSTM-CTC_best_accuracy.pth
