version: '2'
services:
    detection: 
        build:
            context: ../libs/CRAFT
        volumes:
            - /..:/vietscenetext_framework
        # runtime: nvidia
        working_dir: vietscenetext_framework
        command:
            python3 detect_text.py --run_on_folder True --folder_path ../project/data --detection_output_path ../project/detection_output_path --config_pipeline ../project/configs/pipeline.yaml  --config_method ../project/configs/craft.yaml --detection_weight ../project/models/craft_model.pth

    recognition:
        build:
            context: ../libs/MORAN_v2
        volumes:
            - /../:/vietscenetext_framework
        working_dir: vietscenetext_framework
        command:
            python3 recognize_text.py --run_on_folder True --folder_path ../project/data --run_recognition True --run_recognition_with_detection_result True --recognition_weight ../project/models/moranv2_model.pth --detection_output_path ../project/detection_output_path --config_pipeline ../project/configs/pipeline.yaml --config_method ../project/configs/MORANv2.yaml --full_pipeline_output_path ../project/output_full_pipeline
        depends_on:
            -  detection
        # runtime: nvidia
